### ISSUE TITLE
i have a question 

### ISSUE THREAD

**Issue by Jonnycatmeow** [zacksgamerz/funkin-virus#4]
what mod is this 
and im actually wondering

**Comment by zacksgamerz** [comment]
what the fuvk how did u find this

**Comment by Jonnycatmeow** [comment]
idk i just click your name and looked at your respatories

**Comment by zacksgamerz** [comment]
Yeah its a mod. It would be cool if you just ignore everything here, you can help or watch or download if you want to. But please, dont leak it.

**Comment by zacksgamerz** [comment]
Here is the gamejolt page https://gamejolt.com/games/madvirusattack/643489
