### ISSUE TITLE
i wanna say something 

### ISSUE THREAD

**Issue by Jonnycatmeow** [zacksgamerz/funkin-virus#7]
this mod is really good and your music is really good

**Comment by zacksgamerz** [comment]
Thanks, it's a team's work and I'm just the coder.

**Comment by zacksgamerz** [comment]
Thanks again 👍

**Comment by Jonnycatmeow** [comment]
also if you think im gonna put the game on any platform here is my stuff 
gamejolt: https://gamejolt.com/games/Junior-Jonnycats-FNF-Mac-Ports/661502 
https://gamejolt.com/games/Friday-night-funkin-Mac/647285

**Comment by zacksgamerz** [comment]
o dam

**Comment by Jonnycatmeow** [comment]
itch.io: https://jonnycat.itch.io

**Comment by zacksgamerz** [comment]
Nice

**Comment by zacksgamerz** [comment]
I will talk to the leader about it

**Comment by Jonnycatmeow** [comment]
but yeah can i add you on your discord
?

**Comment by Jonnycatmeow** [comment]
i can give you mine

**Comment by Jonnycatmeow** [comment]
Jonnycat#8275

**Comment by Jonnycatmeow** [comment]
there

**Comment by Jonnycatmeow** [comment]
> I will talk to the leader about it

ok 
sounds good too me

**Comment by zacksgamerz** [comment]
Ight ight. I gtg now tho, I will add u tmr.

**Comment by Jonnycatmeow** [comment]
Bet

**Comment by zacksgamerz** [comment]
@!Moon.#6560 I added u. Also you're in
